[font]
size = 14.0

[font.bold]
family = "Hack Nerd Font"
style = "Bold"

[font.italic]
family = "Hack Nerd Font"
style = "Regular Italic"

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[window]
option_as_alt = "Both"
