[[plugins]]
# Python black support.
repo = 'psf/black'
rev = 'stable'
on_ft = ['python']

[[plugins]]
# Golang plugin for minimalists.
repo = 'mattn/vim-goimports'
on_ft = ['go']
hook_add = '''
    let g:goimports_simplify_cmd = 'gofumpt'
'''

[[plugins]]
# Python support for DAP.
repo = 'mfussenegger/nvim-dap-python'
on_ft = ['python']
depends = ['mfussenegger/nvim-dap']

[[plugins]]
# Golang support for DAP.
repo = 'leoluz/nvim-dap-go'
on_ft = ['go']
depends = ['mfussenegger/nvim-dap']
hook_add = '''
lua << EOF
    local ok, dap_go = pcall(require, 'dap-go')
    if ok then
        dap_go.setup()
    end
EOF
'''

# Disabled due to the performance issue.
# [[plugins]]
# # Syntax highlighter.
# repo = 'nvim-treesitter/nvim-treesitter'
# merged = 0
# on_event = 'BufRead'
# hook_post_update = 'TSUpdate'
# hook_add = '''
# lua << EOF
#     require('nvim-treesitter.configs').setup {
#         ensure_installed = 'maintained',
#         highlight = {
#             enable = true,
#         },
#     }
# EOF
# '''
