[[plugins]]
# A colorscheme
repo = 'sainnhe/gruvbox-material'
hook_add = '''
    augroup dein-color-scheme
      autocmd!
      autocmd VimEnter * nested colorscheme gruvbox-material
    augroup END
'''

[[plugins]]
# For :DeinUpdate.
repo = 'wsdjeg/dein-ui.vim'

[[plugins]]
# Lua library for nvim.
repo = 'nvim-lua/plenary.nvim'

[[plugins]]
# Language Server config.
repo = 'neovim/nvim-lspconfig'

[[plugins]]
# Language Server installer.
repo = 'williamboman/nvim-lsp-installer'

[[plugins]]
# Completion plugin.
repo = 'ms-jpq/coq_nvim'
rev = 'coq'

[[plugins]]
# Bundled data for coq_nvim.
repo = 'ms-jpq/coq.artifacts'
rev = 'artifacts'

[[plugins]]
# Outline viewer.
repo = 'stevearc/aerial.nvim'

[[plugins]]
# A fuzzy finder.
repo = 'nvim-telescope/telescope.nvim'
hook_add = '''
    nnoremap <Leader>ff <cmd>Telescope find_files<cr>
    nnoremap <Leader>fg <cmd>Telescope live_grep<cr>
    nnoremap <Leader>fb <cmd>Telescope buffers<cr>
    nnoremap <Leader>fh <cmd>Telescope help_tags<cr>
'''

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
    "" NERDTree configuration
    let g:NERDTreeChDirMode=2
    let g:NERDTreeIgnore=['\.rbc$', '\~$', '\.pyc$', '\.db$', '\.sqlite$', '__pycache__']
    let g:NERDTreeSortOrder=['^__\.py$', '\/$', '*', '\.swp$', '\.bak$', '\~$']
    let g:NERDTreeShowBookmarks=1
    let g:nerdtree_tabs_focus_on_files=1
    let g:NERDTreeMapOpenInTabSilent = '<RightMouse>'
    let g:NERDTreeWinSize = 50
    set wildignore+=*/tmp/*,*.so,*.swp,*.zip,*.pyc,*.db,*.sqlite

    nnoremap <silent> <Leader>nf :NERDTreeFind<CR>
    nnoremap <silent> <Leader>nt :NERDTreeTabsToggle<CR>
'''

[[plugins]]
repo = 'jistr/vim-nerdtree-tabs'
depends = ['nerdtree']

[[plugins]]
# Displays the indention levels with thin vertical lines.
repo = 'Yggdroot/indentLine'

[[plugins]]
# Handles extra whitespaces.
repo = 'ntpeters/vim-better-whitespace'

[[plugins]]
# Shows a git diff in the gutter (sign column) and stages/undoes hunks.
repo = 'airblade/vim-gitgutter'

[[plugins]]
# Detects file type under the cursor according to context.
repo = 'Shougo/context_filetype.vim'

[[plugins]]
# Syntax highlighting for context.
repo = 'osyo-manga/vim-precious'
depends = ['context_filetype.vim']

[[plugins]]
# Git in vim.
repo = 'tpope/vim-fugitive'

[[plugins]]
# Better word object handling.
repo = 'tpope/vim-surround'

[[plugins]]
# Better '.' command.
repo = 'tpope/vim-repeat'

[[plugins]]
# A comment-out plugin.
repo = 'tpope/vim-commentary'

[[plugins]]
# A solid language pack (syntax, indent, etc).
repo = 'sheerun/vim-polyglot'

[[plugins]]
# A better spell checker.
repo = 'kamykn/spelunker.vim'
hook_add = '''
    set nospell  " Turn off builtin spellcheck.

    let g:spelunker_check_type = 2  " Real time spell checking.
    let g:spelunker_disable_uri_checking = 1
    let g:spelunker_disable_email_checking = 1
    let g:spelunker_disable_acronym_checking = 1
    let g:spelunker_disable_backquoted_checking = 1

    " After enabling a colorscheme these highlight groups are cleared.
    " This augroup explicitly enables highlight groups.
    augroup spelunker-colorscheme
        autocmd ColorScheme *
        \ highlight SpelunkerSpellBad cterm=underline ctermfg=247 gui=underline guifg=#9e9e9e |
        \ highlight SpelunkerComplexOrCompoundWord cterm=underline ctermfg=NONE gui=underline guifg=NONE
    augroup enD
'''

