name: docker-build

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: build
        working-directory: ./docker
        run: docker build -t mandaiy/dotfiles:linux-amd64 --platform linux/amd64 .

      - name: login
        uses: actions-hub/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: push
        uses: actions-hub/docker@master
        with:
          args: push mandaiy/dotfiles:linux-amd64
