name: docker-build

on:
  push:
    paths:
      - 'docker/**'
    branches:
      - main

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: docker build -f ./docker/Dockerfile -t mandaiy/dotfiles:linux-amd64 --platform linux/amd64 .
      - uses: actions-hub/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - uses: actions-hub/docker@master
        with:
          args: push mandaiy/dotfiles:linux-amd64
